import { purchaseFullReport, purchaseSubscription } from '../../stripe/stripeConfig';

function PricingCards() {
  return (
    <div className="mt-10 pt-8 border-t border-slate-200">
      {/* Generated By */}
      <div className="text-center mb-8">
        <p className="text-xs text-secondary">
          Generated by <span className="font-semibold text-primary">PathPilot</span> &mdash; $15 automated career analysis
        </p>
      </div>

      {/* Payment CTAs */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5 max-w-2xl mx-auto">
        {/* One-Time Report */}
        <div className="group relative bg-white rounded-2xl border-2 border-accent/20 p-6 hover:border-accent hover:shadow-xl transition-all duration-300 text-center">
          <div className="absolute -top-3 left-1/2 -translate-x-1/2">
            <span className="bg-accent text-white text-xs font-bold px-4 py-1 rounded-full shadow-md">Most Popular</span>
          </div>
          <div className="mt-3">
            <div className="text-4xl font-extrabold text-primary">$15</div>
            <p className="text-sm text-secondary mt-1">one-time</p>
          </div>
          <h4 className="font-bold text-primary text-lg mt-4">Full Career Report</h4>
          <ul className="mt-3 space-y-2 text-left">
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-accent mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Complete salary benchmarking
            </li>
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-accent mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Full skill gap analysis
            </li>
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-accent mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Career trajectory map
            </li>
          </ul>
          <button
            onClick={purchaseFullReport}
            className="mt-5 inline-flex items-center justify-center gap-2 w-full px-6 py-3 rounded-xl bg-accent text-white text-sm font-bold hover:bg-accent/90 hover:shadow-lg transition-all shadow-md cursor-pointer"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
            Upgrade to Full Report — $15
          </button>
        </div>

        {/* Subscription */}
        <div className="relative bg-white rounded-2xl border-2 border-slate-200 p-6 hover:border-primary hover:shadow-xl transition-all duration-300 text-center">
          <div className="mt-3">
            <div className="text-4xl font-extrabold text-primary">$9</div>
            <p className="text-sm text-secondary mt-1">per month</p>
          </div>
          <h4 className="font-bold text-primary text-lg mt-4">Ongoing Monitoring</h4>
          <ul className="mt-3 space-y-2 text-left">
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-primary mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Monthly market updates
            </li>
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-primary mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Skill-gap alerts
            </li>
            <li className="flex items-start gap-2 text-sm text-gray-600">
              <svg className="w-4 h-4 text-primary mt-0.5 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Salary trend tracking
            </li>
          </ul>
          <button
            onClick={purchaseSubscription}
            className="mt-5 inline-flex items-center justify-center gap-2 w-full px-6 py-3 rounded-xl bg-primary text-white text-sm font-bold hover:bg-primary/90 hover:shadow-lg transition-all shadow-md cursor-pointer"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Subscribe $9/mo
          </button>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-8 bg-slate-50 rounded-xl p-4 text-center border border-slate-100">
        <p className="text-xs text-secondary">
          This analysis is based on aggregated market data and your self-reported information.
          For personalized career coaching, consider a premium consultation.
        </p>
      </div>
    </div>
  );
}

export default PricingCards;
